config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  root 'top#index'
  # root 'communities/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
  end
  resources :users, only:[:show]
  resources :messages, only:[:new, :create, :index]
  resources :friends, only:[:index, :new, :create, :destroy] do
    member do
      post :accept
    end
  end
  resources :communities do
    member do
      resources :participants, only:[:create, :destroy]
    end
    resources :posts, only:[:new, :create]
  end
  resources :games, only:[:new, :create]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :myself, class_name: "User"
  belongs_to :partner, class_name: "User"
  has_many :messages, dependent: :destroy

  # def self.friend_search(friends, name_search)
  #   friends.each do |friend|
  #     @partners.store(friend.partner)
  #   end
  #   @friends = @partners.where('name LIKE ?', "%#{name_search}")
  #   binding.irb
  # end

  # def friend_request!(partner)
  #   active_friends.create!(request: false, partner_id: partner.id)
  # end
  #
  # def friend_accept!(partner)
  #   active_friends.create!(request: true, partner_id: partner.id)
  # end
  #
  # def friendly?(partner)
  #   active_friends.find_by(partner_id: partner.id)
  # end
  #
  # def unfriend(partner)
  #   active_friends.find_by(partner_id: partner.id).destroy
  # end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  respond_to? :js

  def index
    @friends = current_user.active_friends
  end

  def new
    @users = User.all
    @users = @users.where('name LIKE ?', "%#{params[:name_search]}%") if params[:name_search].present?
  end

  def create
    @user = User.find(params[:friend][:partner_id])
    current_user.friend_request!(@user)
  end

  def accept
    @friend = Friend.find(params[:request_id])
    @user = User.find(@friend.myself_id)
    @friend.request = true
    @friend.save
    current_user.friend_accept!(@user)
    redirect_to user_path(current_user.id)
  end

  def destroy
    @request = Friend.find(params[:id])
    if @request.request?
      @user = @request.partner
      current_user.elimination(@user)
    else
      @user = @request.myself
      current_user.unfriend(@user)
    end
    redirect_to user_path(current_user.id)
  end

  private

  def friend_params
    params.permit(:myself_id, :partner_id)
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_friend_form.html.erb
<div id="friend_form_<%= user.id %>">
  <% unless current_user.friendly?(user) %>
    <%= form_with(model: current_user.active_friends.build(partner_id: user.id))  do |f| %>
      <%= f.hidden_field :partner_id %>
      <%= f.submit t('view.friend_request'), {class: "btn btn-primary"} %>
    <% end %>
  <% else %>
    <p>申請中</p>
  <% end %>
</div>

app/views/friends/create.js.erb
$("#friend_form_"+"<%= @user.id %>").html("<%= escape_javascript(render partial: 'users/friend_form', locals: { user: @user } ) %>")

app/views/friends/destroy.js.erb
$("#friend_form_"+"<%= @user.id %>").html("<%= escape_javascript(render partial: 'users/friend_form', locals: { user: @user } ) %>")

app/views/friends/index.html.erb
<h3 class="page">フレンド一覧</h3>
<div class="container">
  <div class="row">
    <ul class="list-group">
      <% @friends.each do |friend| %>
        <% if friend.request %>
          <li class="list-group-item list-group-item-action">
            ユーザー名：<%= friend.partner.name %>
            ｜<%= link_to t('view.friend_page'), user_path(friend.partner.id) %>
            ｜<%= link_to t('view.friend_elimination'), friend_path(friend.id), method: :delete %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/friends/new.html.erb
<h3 class="page">フレンド申請</h3>
<% if params[:info] %>
  <p class="alert alert-danger"><%= params[:info] %></p>
<% end %>
<div class="container">
  <div class="row">
    <%= form_with(url: new_friend_path, method: :get, local: true) do |form| %>
      <%= form.label :name, t('view.user_name') %>
      <%= form.text_field :name_search, placeholder: "ユーザー名を入力" %>

      <%= form.submit t('view.search') %>
    <% end %>
    <ul class="list-group">
        <% @users.each do |user| %>
          <% unless current_user.friendly?(user) or current_user == user %>
          <li class="list-group-item list-group-item-action mb-3">
            ユーザー名：<%= user.name %><br>
            メールアドレス：<%= user.email %>
            <%= render 'friend_form', user: user %>
          </li>
          <% end %>
        <% end %>
    </ul>
  </div>
</div>