config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  root 'top#index'
  # root 'communities/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
  end
  resources :users, only:[:show]
  resources :messages, only:[:new, :create, :index]
  resources :friends, only:[:index, :new, :create, :destroy] do
    member do
      post :accept
    end
  end
  resources :communities do
    member do
      resources :participants, only:[:create, :destroy]
    end
    resources :posts, only:[:new, :create]
  end
  resources :games, only:[:new, :create]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :participants, dependent: :destroy
  has_many :join_communities, through: :participants, source: :community
  has_many :posts, dependent: :destroy
  has_many :communities, through: :posts
  has_many :messages, dependent: :destroy

  has_many :active_friends, foreign_key: 'myself_id', class_name: 'Friend', dependent: :destroy
  has_many :passive_friends, foreign_key: 'partner_id', class_name: 'Friend', dependent: :destroy
  has_many :contact, through: :active_friends, source: :partner
  has_many :receive, through: :passive_friends, source: :myself

  has_one :message_read, dependent: :destroy

  after_create_commit :message_read_create

  def friend_request!(partner)
    active_friends.create!(request: false, partner_id: partner.id)
  end

  def friend_accept!(partner)
    active_friends.create!(request: true, partner_id: partner.id)
  end

  def friendly?(partner)
    active_friends.find_by(partner_id: partner.id)
  end

  def unfriend(myself)
    passive_friends.find_by(myself_id: myself.id).destroy
  end

  def elimination(partner)
    active_friends.find_by(partner_id: partner.id).destroy
    passive_friends.find_by(myself_id: partner.id).destroy
  end

  def message_read_create
    user = User.last
    user.create_message_read!(user_id: user.id, message_read_last: 0)
  end

  def self.push_message(current_user)
    messages = Message.where(destination: current_user.id).order(created_at: "DESC")
    if messages.present?
      if current_user.message_read.message_read_last < messages[0].id
        current_user.message_read.update(message_read_last: messages[0].id)
        return true
      end
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'guest'
      user.admin = false
    end
  end

  def self.admin_guest
    find_or_create_by!(email: 'admin_guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'admin_guest'
      user.admin = true
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def new_admin_guest
    user = User.admin_guest
    sign_in user
    redirect_to root_path, notice: '管理者ゲストユーザーとしてログインしました。'
  end
  
  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.message_read_create(@user)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @request = @user.passive_friends.where(request: false)
    @communities = @user.join_communities
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin_flag)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_form.html.erb
<div id="friend_form_<%= user.id %>">
  <% unless current_user.friendly?(user) %>
    <%= form_with(model: current_user.active_friends.build(partner_id: user.id))  do |f| %>
      <%= f.hidden_field :partner_id %>
      <%= f.submit "申請する" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_friends.find_by(partner_id: user.id), method: :delete ) do |f| %>
      <p>申請中</p>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<h2>ユーザー</h2>
<% @users.each do |user| %>
  <%= user.name %>
  <%= user.email %>
  <%= render 'friend_form', user: user %>
<% end %>

app/views/users/show.html.erb
<h3 class="page"><%= @user.name %>のユーザーページ</h3>
<div class="container">
  <div class="row">
    <h4 class="sticky-top info text-center">参加コミュニティ一覧</h4>
  <% if @request.present? and @user == current_user %>
      <% @request.each do |request| %>
        <div class="card">
          <div class="card-header">
            <p>ユーザー名：<%= request.myself.name %></p>
          </div>
          <div class="list-group list-group-flush">
            <li class="list-group-item">
              <%= button_to t('view.accept'), { controller: 'friends', action: 'accept', params: {request_id: request.id} }, {class: "btn btn-primary"} %>
            </li>
            <li class="list-group-item">
              <%= button_to t('view.unfriend'), { controller: 'friends', action: 'destroy', params: {id: request.id} }, {method: :delete, class: "btn btn-danger"} %>
            </li>
          </div>
        </div>
      <% end %>
  <% end %>
  </div>
  <div class="row">
      <% @communities.each do |community| %>
        <div class="card" style="width: 18rem;">
          <%= image_tag(community.icon.url, size: '320x240', class: "card-img-top") %>
          <div class="card-body">
            <h4 class="card-title"><%= community.name %></h4>
            <h5 class="card-title"><%= community.game.name %></h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">紹介文:<%= community.comment %></li>
              <li class="list-group-item">
                <% community.tags.each do |tag| %>
                  <%= tag.name %>
                <% end %>
              </li>
              <% if community.posts.present? %>
                <li class="list-group-item">最終更新日<%= community.posts.last.created_at.strftime("%Y-%m-%d %H:%M:%S") %></li>
              <% end %>
            </ul>
            <%= link_to t('view.show'), community, class: "btn btn-primary" %>
            <%if community.create_user_id == current_user.id or current_user.try(:admin?) %>
              <div class="btn_action">
                <%= link_to t('view.edit'), edit_community_path(community), class: "btn btn-outline-success" %>
                <%= link_to t('view.destroy'), community, method: :delete, data: { confirm: t('view.confirm') }, class: "btn btn-outline-danger" %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
  </div>
</div>