config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  root 'top#index'
  # root 'communities/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
  end
  resources :users, only:[:show]
  resources :messages, only:[:new, :create, :index]
  resources :friends, only:[:index, :new, :create, :destroy] do
    member do
      post :accept
    end
  end
  resources :communities do
    member do
      resources :participants, only:[:create, :destroy]
    end
    resources :posts, only:[:new, :create]
  end
  resources :games, only:[:new, :create]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # def self.push_message
  #   if user_signed_in?
  #     messages = Message.where(destination: current_user.id).order(created_at: "DESC")
  #     if current_user.message_read.message_read_last < messages[0]
  #       current_user.message_read.message_read_last = messages[0]
  #       return true
  #     end
  #   end
  # end
end

app/models/community.rb
class Community < ApplicationRecord
  validates :name, presence: true
  validates :comment, presence: true

  belongs_to :game

  has_many :community_tags, dependent: :destroy
  has_many :tags, through: :community_tags

  has_many :participants, dependent: :destroy
  has_many :join_users, through: :participants, source: :user
  has_many :posts, dependent: :destroy
  has_many :posting_users, through: :posts, source: :user

  mount_uploader :icon, IconUploader

  def community_participation(user)
    participants.create(user_id: user)
  end
  #
  # def community_secession(user)
  #   binding.irb
  #   participants.destroy(user_id: user)
  # end
end

app/models/community_tag.rb
class CommunityTag < ApplicationRecord
  belongs_to :tag
  belongs_to :community
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :myself, class_name: "User"
  belongs_to :partner, class_name: "User"
  has_many :messages, dependent: :destroy

  # def self.friend_search(friends, name_search)
  #   friends.each do |friend|
  #     @partners.store(friend.partner)
  #   end
  #   @friends = @partners.where('name LIKE ?', "%#{name_search}")
  #   binding.irb
  # end

  # def friend_request!(partner)
  #   active_friends.create!(request: false, partner_id: partner.id)
  # end
  #
  # def friend_accept!(partner)
  #   active_friends.create!(request: true, partner_id: partner.id)
  # end
  #
  # def friendly?(partner)
  #   active_friends.find_by(partner_id: partner.id)
  # end
  #
  # def unfriend(partner)
  #   active_friends.find_by(partner_id: partner.id).destroy
  # end
end

app/models/game.rb
class Game < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :info, presence: true
  has_many :communities
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :friend
  belongs_to :user
  mount_uploader :message_image, ImageUploader
end

app/models/message_read.rb
class MessageRead < ApplicationRecord
  belongs_to :user
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :community
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :community

  mount_uploader :image, ImageUploader
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :community_tags, dependent: :destroy
  has_many :communities, through: :community_tags
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :participants, dependent: :destroy
  has_many :join_communities, through: :participants, source: :community
  has_many :posts, dependent: :destroy
  has_many :communities, through: :posts
  has_many :messages, dependent: :destroy

  has_many :active_friends, foreign_key: 'myself_id', class_name: 'Friend', dependent: :destroy
  has_many :passive_friends, foreign_key: 'partner_id', class_name: 'Friend', dependent: :destroy
  has_many :contact, through: :active_friends, source: :partner
  has_many :receive, through: :passive_friends, source: :myself

  has_one :message_read, dependent: :destroy

  after_create_commit :message_read_create

  def friend_request!(partner)
    active_friends.create!(request: false, partner_id: partner.id)
  end

  def friend_accept!(partner)
    active_friends.create!(request: true, partner_id: partner.id)
  end

  def friendly?(partner)
    active_friends.find_by(partner_id: partner.id)
  end

  def unfriend(myself)
    passive_friends.find_by(myself_id: myself.id).destroy
  end

  def elimination(partner)
    active_friends.find_by(partner_id: partner.id).destroy
    passive_friends.find_by(myself_id: partner.id).destroy
  end

  def message_read_create
    user = User.last
    user.create_message_read!(user_id: user.id, message_read_last: 0)
  end

  def self.push_message(current_user)
    messages = Message.where(destination: current_user.id).order(created_at: "DESC")
    if messages.present?
      if current_user.message_read.message_read_last < messages[0].id
        current_user.message_read.update(message_read_last: messages[0].id)
        return true
      end
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'guest'
      user.admin = false
    end
  end

  def self.admin_guest
    find_or_create_by!(email: 'admin_guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'admin_guest'
      user.admin = true
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/push.js/1.0.12/push.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <!-- drawer.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.1/css/drawer.min.css">
    <!-- jquery & iScroll -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.1.3/iscroll.min.js"></script>
    <!-- drawer.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.1/js/drawer.min.js"></script>
  </head>
  <body>
    <% if user_signed_in? %>
      <% if User.push_message(current_user) %>
        <script>
          Push.create("新着メッセージがあります"), {
              timeout: 4000,
              onClick: function () {
                  window.focus();
                  this.close();
              }
          };
        </script>
      <% end %>
    <% end %>
  <header>
    <h1 class="title"><%= image_tag("touka.png", size: '200x80') %></h1>
    <ul class="menu-group">
    <% if user_signed_in? %>
      <li class="header-menu"><%= link_to t('view.logout'), destroy_user_session_path, method: :delete, class: "btn btn-info" %></li>
      <% if request.path_info != communities_path %>
        <li class="header-menu"><%= link_to t('view.community_index'), communities_path, class: "btn btn-info" %></li>
      <% end %>
      <% if request.path_info != user_path(current_user) %>
        <li class="header-menu"><%= link_to t('view.my_page'), user_path(current_user), class: "btn btn-info" %></li>
      <% end %>
      <% if request.path_info != friends_path %>
        <li class="header-menu"><%= link_to t('view.friend_index'), friends_path, class: "btn btn-info" %></li>
      <% end %>
      <% if request.path_info != messages_path %>
        <li class="header-menu"><%= link_to t('view.messages_page'), messages_path, class: "btn btn-info" %></li>
      <% end %>
      <% if current_user.admin %>
        <li class="header-menu"><%= link_to t('view.admin_page'), rails_admin_path, class: "btn btn-info" %></li>
      <% end %>
    <% else %>
      <li class="header-menu"><%= link_to t('view.guest_page'), users_guest_sign_in_path, method: :post, class: "login btn btn-info" %></li>
      <li class="header-menu"><%= link_to t('view.admin_guest_page'), users_admin_guest_sign_in_path, method: :post, class: "login btn btn-info" %></li>
      <li class="header-menu"><%= link_to t('view.login'), new_user_session_path, class: "btn btn-info" %></li>
      <li class="header-menu"><%= link_to t('view.signin'), new_user_registration_path, class: "btn btn-info" %></li>
      <li class="header-menu"><%= link_to t('view.community_index'), communities_path, class: "btn btn-info" %></li>
    <% end %>
    </ul>
    <% if notice %>
      <p class="alert alert-primary"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <% if user_signed_in? %>
      <body class="drawer drawer--left">
      <div role="banner">
    <!-- ハンバーガーボタン -->
        <button type="button" class="drawer-toggle drawer-hamburger bg-primary">
          <span class="sr-only">toggle navigation</span>
          <span class="drawer-hamburger-icon"></span>
        </button>
    <!-- ナビゲーションの中身 -->
        <nav class="drawer-nav bg-secondary" role="navigation">
          <ul class="drawer-menu list-group">
            <li class="list-group-item list-group-item-primary"><h3 class="drawer-brand">LinkPlayer</h3></li>
            <li class="list-group-item list-group-item-primary">カーソルをボタンに合わせると説明が表示されます</li>
            <li class="list-group-item text-center bg-secondary"><%= link_to t('view.create_game'), new_game_path, class: "btn btn-success mb-3", 'data-toggle': :tooltip, 'data-placement': :'right', 'title': :'題材にしたいゲームが無い場合はここから新しく登録出来ます' %></li>
            <li class="list-group-item text-center bg-secondary"><%= link_to t('view.community_create'), new_community_path, class: "btn btn-success mb-3", 'data-toggle': :tooltip, 'data-placement': :'right', 'title': :'新規作成には題材とするゲームが必要なので存在しない場合は先にゲーム登録をしてください' %></li>
            <li class="list-group-item text-center bg-secondary"><%= link_to t('view.message_create'), new_message_path, class: "btn btn-primary mb-3", 'data-toggle': :tooltip, 'data-placement': :'right', 'title': :'フレンドへのメッセージ作成画面に移動します' %></li>
            <li class="list-group-item text-center bg-secondary"><%= link_to t('view.receives_index'), messages_path(output: true), class: "btn btn-warning mb-3", 'data-toggle': :tooltip, 'data-placement': :'right', 'title': :'フレンドから受信したメッセージ一覧を表示します' %></li>
            <li class="list-group-item text-center bg-secondary"><%= link_to t('view.sends_index'), messages_path(output: nil), class: "btn btn-success mb-3", 'data-toggle': :tooltip, 'data-placement': :'right', 'title': :'フレンドに送信したメッセージ一覧を表示します' %></li>
            <li class="list-group-item text-center bg-secondary"><%= link_to t('view.create_friend'), new_friend_path, class: "btn btn-success mb-3", 'data-toggle': :tooltip, 'data-placement': :'right', 'title': :'フレンド申請画面に移動します' %></li>
          </ul>
        </nav>
      </div>
      <main role="main">
    </main>
    <!-- drawer利用の宣言 -->
      <script>
        $(document).ready(function() {
        $('.drawer').drawer(); });
      </script>

    </body>
  <% end %>
  </header>
    <%= yield %>
    <footer class="fixed-bottom">LinkPlayer</footer>
  </body>
</html>